server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-components: always
      #show-details: always
  info:
    java:
      enabled: true
    os:
      enabled: true

info:
  app:
    name: hello-actuator
    company: test
